[package]
name = "gambling-machine"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
rsb_derive = "0.5.1"
slack-morphism = { version = "2.7", features = ["hyper", "axum"] }
tokio = "1.42.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
